[build]
  command = "npm run build"
  functions = "netlify/functions"
  publish = "."

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

[dev]
  command = "echo 'Development server running'"
  port = 8888
  targetPort = 8888
  publish = "."
  autoLaunch = true

# Environment variables (set these in Netlify dashboard or .env file)
# DATABASE_URL = "postgresql://user:password@host/database"
# STRIPE_SECRET_KEY = "sk_test_..."
# STRIPE_PUBLISHABLE_KEY = "pk_test_..."
